version: "3"

services:
    mssql:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_Password1!"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433